# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml


formatter:
  trailing_commas: preserve

analyzer:
  exclude: 
    - '**/*.g.dart'

linter:
  rules:
    #Prefer const with constant constructors.
    prefer_const_constructors: true

    #Avoid setters without getters.
    avoid_setters_without_getters: true

    #Declare method return types.
    always_declare_return_types: true

    #Don't import implementation files from another package.
    implementation_imports: true

    #Don't specify the late modifier when it is not needed.
    unnecessary_late: true

    #Avoid .toString() in production code since results may be minified.
    avoid_type_to_string: true

    avoid_classes_with_only_static_members: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: true
    # avoid_positional_boolean_parameters: true
    avoid_print: true
    avoid_types_on_closure_parameters: true
    camel_case_extensions: true
    camel_case_types: true
    comment_references: true
    constant_identifier_names: true
    # flutter_style_todos: true
    literal_only_boolean_expressions: false
    non_constant_identifier_names: true
    one_member_abstracts: true
    overridden_fields: true
    # prefer_constructors_over_static_methods: true
    prefer_function_declarations_over_variables: true
    prefer_interpolation_to_compose_strings: true
    # sort_constructors_first: true
    type_annotate_public_apis: false
    unnecessary_brace_in_string_interps: true
    unnecessary_statements: true
    unnecessary_this: true
#    use_setters_to_change_properties: true
    no_leading_underscores_for_local_identifiers: false  
