name: prenumerata
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.8

  #Widgets
  loader_overlay: ^5.0.0

  # Animation & Graphics
  flutter_animate: ^4.5.2
  flutter_svg: ^2.1.0


  # Hardware
  sensors_plus: ^4.0.0
  
  #Native
  path_provider: ^2.1.5
  path: ^1.9.1

  # State Management
  flutter_bloc: ^9.1.1
  provider: ^6.1.5

  # Database & Storage
  objectbox: ^4.2.0
  objectbox_flutter_libs: ^4.2.0

  #DI
  get_it: ^8.0.3

  # Utilities
  equatable: ^2.0.7
  logging: ^1.3.0
  flutter_native_splash: ^2.4.6
  collection: ^1.19.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_gen: ^5.10.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15
  objectbox_generator: ^4.2.0

  
flutter:
  uses-material-design: true

  assets:
    - assets/svgs/logos/

  fonts:

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500  
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600 
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700   


flutter_gen:
  assets:
    outputs:
      style: camel-case
  output: lib/generated/
  line_length: 120
  integrations:
    flutter_svg: false






























